/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QFrame *line;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label;
    QLabel *label_23;
    QLabel *label_38;
    QLineEdit *codigo_locacion;
    QLineEdit *nombre_latitud;
    QLabel *label_39;
    QDoubleSpinBox *latitud_locacion;
    QLabel *label_40;
    QDoubleSpinBox *longitud_locacion;
    QLabel *label_41;
    QLineEdit *pass_locacion;
    QLabel *label_42;
    QLineEdit *archivo_locacion;
    QFrame *line_3;
    QLabel *label_43;
    QLabel *label_44;
    QLineEdit *destino_arista;
    QLabel *label_45;
    QDoubleSpinBox *multiplicador_arista;
    QLabel *label_46;
    QLineEdit *inicio_arista;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QFrame *line_4;
    QPushButton *pushButton_30;
    QFrame *line_5;
    QLabel *label_47;
    QLineEdit *eliminar_localidad;
    QPushButton *pushButton_31;
    QWidget *page_2;
    QLabel *label_2;
    QLabel *label_52;
    QLineEdit *dpi_donacion;
    QLabel *label_53;
    QLineEdit *nombres_donacion;
    QLabel *label_54;
    QLineEdit *apellidos_donacion;
    QLabel *label_55;
    QLineEdit *fecha_donacion;
    QLabel *label_56;
    QLineEdit *monto_donacion;
    QPushButton *pushButton_34;
    QWidget *page_3;
    QLabel *label_3;
    QLabel *label_10;
    QLineEdit *lineEdit;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QLabel *label_11;
    QLineEdit *lineEdit_2;
    QPushButton *pushButton_16;
    QFrame *line_2;
    QLabel *label_12;
    QLabel *label_13;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QFrame *line_7;
    QFrame *line_8;
    QPushButton *Carchivo_informacion;
    QLabel *label_51;
    QPushButton *MArchivo_informacion;
    QLineEdit *archivo_informacion;
    QLabel *Estado;
    QWidget *page_4;
    QLabel *label_4;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QStackedWidget *dock_albergue;
    QWidget *page_7;
    QLabel *label_6;
    QLabel *label_14;
    QLineEdit *familia_albergue;
    QStackedWidget *stackedWidget_2;
    QWidget *page_11;
    QLabel *label_15;
    QLineEdit *nombre_familia;
    QLabel *label_16;
    QLineEdit *apellidos_familia;
    QLabel *label_17;
    QLineEdit *edad_familia;
    QLabel *label_18;
    QPushButton *btn_agregarFamilia;
    QLineEdit *genero_familia;
    QWidget *page_12;
    QWidget *page_10;
    QLabel *label_9;
    QLineEdit *nombre_individuo;
    QLineEdit *apellidos_individuo;
    QLabel *label_24;
    QLineEdit *edad_individuo;
    QLabel *label_25;
    QLabel *label_26;
    QPushButton *btn_agregarPersona;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *dpi_individuo;
    QLabel *label_37;
    QLineEdit *dpi_familia;
    QLineEdit *genero_individuo;
    QWidget *page_8;
    QLabel *label_7;
    QStackedWidget *dock_familia;
    QWidget *page_13;
    QWidget *page_14;
    QComboBox *Cfamilia_modificar;
    QLabel *label_29;
    QLabel *label_30;
    QComboBox *cIndividuo_modificar;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLineEdit *nombre_modificar;
    QLineEdit *apellidos_modificar;
    QLineEdit *edad_modificar;
    QLineEdit *genero_modificar;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QWidget *page_9;
    QLabel *label_8;
    QLabel *label_35;
    QComboBox *cFamilia_eliminar;
    QComboBox *Cindividuo_eliminar;
    QLabel *label_36;
    QPushButton *eliminar_familia;
    QPushButton *eliminar_familia_2;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_10;
    QWidget *page_5;
    QLabel *label_5;
    QLabel *label_20;
    QLineEdit *acopio_categoria;
    QLabel *label_21;
    QLineEdit *acopio_nombre;
    QLabel *label_22;
    QSpinBox *spinBox;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QTextEdit *textEdit_2;
    QPushButton *pushButton_37;
    QWidget *page_6;
    QLabel *label_19;
    QPushButton *pushButton_23;
    QWidget *gridLayoutWidget;
    QGridLayout *gridLayout;
    QPushButton *pushButton_32;
    QFrame *line_6;
    QComboBox *puntoa;
    QComboBox *puntob;
    QLabel *label_48;
    QLabel *label_49;
    QWidget *page_15;
    QLabel *label_50;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLineEdit *categoria_entrega;
    QLineEdit *nombre_entrega;
    QLineEdit *unidades_entrega;
    QTextEdit *lst_entrega;
    QFrame *line_9;
    QLabel *label_60;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_33;
    QMenuBar *menuBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(752, 671);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(20, 20, 89, 71));
        QIcon icon;
        icon.addFile(QStringLiteral(":/Imagenes/ubicacion.png"), QSize(), QIcon::Normal, QIcon::On);
        pushButton->setIcon(icon);
        pushButton->setIconSize(QSize(50, 60));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(20, 110, 89, 71));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/Imagenes/210485.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_2->setIcon(icon1);
        pushButton_2->setIconSize(QSize(60, 60));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(20, 200, 89, 71));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/Imagenes/img_evaluacion_ipo.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_3->setIcon(icon2);
        pushButton_3->setIconSize(QSize(125, 125));
        pushButton_4 = new QPushButton(centralWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(20, 290, 89, 71));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/Imagenes/familia.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_4->setIcon(icon3);
        pushButton_4->setIconSize(QSize(75, 50));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(130, 10, 20, 621));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(150, 10, 571, 631));
        stackedWidget->setFrameShape(QFrame::NoFrame);
        stackedWidget->setMidLineWidth(0);
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        label = new QLabel(page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 67, 17));
        label_23 = new QLabel(page);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(20, 90, 67, 17));
        label_38 = new QLabel(page);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(20, 50, 67, 17));
        codigo_locacion = new QLineEdit(page);
        codigo_locacion->setObjectName(QStringLiteral("codigo_locacion"));
        codigo_locacion->setGeometry(QRect(90, 50, 211, 25));
        nombre_latitud = new QLineEdit(page);
        nombre_latitud->setObjectName(QStringLiteral("nombre_latitud"));
        nombre_latitud->setGeometry(QRect(90, 80, 211, 25));
        label_39 = new QLabel(page);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(20, 130, 67, 17));
        latitud_locacion = new QDoubleSpinBox(page);
        latitud_locacion->setObjectName(QStringLiteral("latitud_locacion"));
        latitud_locacion->setGeometry(QRect(90, 120, 69, 26));
        latitud_locacion->setMinimum(-335.99);
        latitud_locacion->setMaximum(205.99);
        latitud_locacion->setValue(0);
        label_40 = new QLabel(page);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(170, 130, 67, 17));
        longitud_locacion = new QDoubleSpinBox(page);
        longitud_locacion->setObjectName(QStringLiteral("longitud_locacion"));
        longitud_locacion->setGeometry(QRect(240, 120, 69, 26));
        longitud_locacion->setMinimum(-335.99);
        longitud_locacion->setMaximum(205.99);
        longitud_locacion->setValue(0);
        label_41 = new QLabel(page);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(20, 170, 67, 17));
        pass_locacion = new QLineEdit(page);
        pass_locacion->setObjectName(QStringLiteral("pass_locacion"));
        pass_locacion->setGeometry(QRect(100, 160, 201, 25));
        label_42 = new QLabel(page);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(20, 210, 141, 17));
        archivo_locacion = new QLineEdit(page);
        archivo_locacion->setObjectName(QStringLiteral("archivo_locacion"));
        archivo_locacion->setGeometry(QRect(142, 200, 151, 25));
        line_3 = new QFrame(page);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(340, 40, 20, 251));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_43 = new QLabel(page);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(370, 40, 67, 17));
        label_44 = new QLabel(page);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(370, 124, 67, 17));
        destino_arista = new QLineEdit(page);
        destino_arista->setObjectName(QStringLiteral("destino_arista"));
        destino_arista->setGeometry(QRect(370, 144, 171, 25));
        label_45 = new QLabel(page);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(370, 190, 101, 21));
        multiplicador_arista = new QDoubleSpinBox(page);
        multiplicador_arista->setObjectName(QStringLiteral("multiplicador_arista"));
        multiplicador_arista->setGeometry(QRect(470, 184, 69, 26));
        multiplicador_arista->setMinimum(-335.99);
        multiplicador_arista->setMaximum(205.99);
        multiplicador_arista->setValue(0);
        label_46 = new QLabel(page);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(370, 74, 67, 17));
        inicio_arista = new QLineEdit(page);
        inicio_arista->setObjectName(QStringLiteral("inicio_arista"));
        inicio_arista->setGeometry(QRect(370, 94, 171, 25));
        pushButton_28 = new QPushButton(page);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(30, 260, 281, 25));
        pushButton_29 = new QPushButton(page);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(360, 260, 201, 25));
        line_4 = new QFrame(page);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(20, 300, 561, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        pushButton_30 = new QPushButton(page);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(30, 320, 531, 25));
        line_5 = new QFrame(page);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(20, 360, 551, 16));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_47 = new QLabel(page);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(220, 380, 181, 20));
        eliminar_localidad = new QLineEdit(page);
        eliminar_localidad->setObjectName(QStringLiteral("eliminar_localidad"));
        eliminar_localidad->setGeometry(QRect(50, 410, 501, 25));
        pushButton_31 = new QPushButton(page);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(98, 450, 371, 25));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        label_2 = new QLabel(page_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 10, 67, 17));
        label_52 = new QLabel(page_2);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(20, 40, 201, 17));
        dpi_donacion = new QLineEdit(page_2);
        dpi_donacion->setObjectName(QStringLiteral("dpi_donacion"));
        dpi_donacion->setGeometry(QRect(20, 70, 331, 25));
        label_53 = new QLabel(page_2);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(20, 110, 67, 17));
        nombres_donacion = new QLineEdit(page_2);
        nombres_donacion->setObjectName(QStringLiteral("nombres_donacion"));
        nombres_donacion->setGeometry(QRect(20, 140, 331, 25));
        label_54 = new QLabel(page_2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(20, 180, 67, 17));
        apellidos_donacion = new QLineEdit(page_2);
        apellidos_donacion->setObjectName(QStringLiteral("apellidos_donacion"));
        apellidos_donacion->setGeometry(QRect(20, 210, 331, 25));
        label_55 = new QLabel(page_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(20, 250, 67, 17));
        fecha_donacion = new QLineEdit(page_2);
        fecha_donacion->setObjectName(QStringLiteral("fecha_donacion"));
        fecha_donacion->setGeometry(QRect(20, 270, 331, 25));
        label_56 = new QLabel(page_2);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(20, 310, 67, 17));
        monto_donacion = new QLineEdit(page_2);
        monto_donacion->setObjectName(QStringLiteral("monto_donacion"));
        monto_donacion->setGeometry(QRect(20, 340, 331, 25));
        pushButton_34 = new QPushButton(page_2);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(30, 420, 221, 25));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        label_3 = new QLabel(page_3);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(0, 10, 91, 17));
        label_10 = new QLabel(page_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 40, 67, 17));
        lineEdit = new QLineEdit(page_3);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(10, 60, 291, 25));
        pushButton_11 = new QPushButton(page_3);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(10, 100, 111, 25));
        pushButton_12 = new QPushButton(page_3);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(140, 100, 121, 25));
        pushButton_13 = new QPushButton(page_3);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(20, 150, 161, 25));
        pushButton_14 = new QPushButton(page_3);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(150, 290, 121, 25));
        pushButton_15 = new QPushButton(page_3);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(30, 330, 161, 25));
        label_11 = new QLabel(page_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(20, 230, 67, 17));
        lineEdit_2 = new QLineEdit(page_3);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(20, 250, 291, 25));
        pushButton_16 = new QPushButton(page_3);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(20, 290, 111, 25));
        line_2 = new QFrame(page_3);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(20, 180, 561, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_12 = new QLabel(page_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(370, 40, 171, 121));
        label_12->setPixmap(QPixmap(QString::fromUtf8(":/Imagenes/localizacion-tienda-ropa.png")));
        label_12->setScaledContents(true);
        label_12->setAlignment(Qt::AlignCenter);
        label_12->setWordWrap(true);
        label_13 = new QLabel(page_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(370, 220, 181, 151));
        label_13->setPixmap(QPixmap(QString::fromUtf8(":/Imagenes/medicina.png")));
        label_13->setScaledContents(true);
        pushButton_24 = new QPushButton(page_3);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(40, 580, 89, 25));
        pushButton_25 = new QPushButton(page_3);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(390, 580, 89, 25));
        line_7 = new QFrame(page_3);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 560, 561, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(page_3);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(10, 380, 571, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        Carchivo_informacion = new QPushButton(page_3);
        Carchivo_informacion->setObjectName(QStringLiteral("Carchivo_informacion"));
        Carchivo_informacion->setGeometry(QRect(30, 460, 121, 25));
        label_51 = new QLabel(page_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(20, 400, 67, 17));
        MArchivo_informacion = new QPushButton(page_3);
        MArchivo_informacion->setObjectName(QStringLiteral("MArchivo_informacion"));
        MArchivo_informacion->setGeometry(QRect(170, 460, 121, 25));
        archivo_informacion = new QLineEdit(page_3);
        archivo_informacion->setObjectName(QStringLiteral("archivo_informacion"));
        archivo_informacion->setGeometry(QRect(20, 420, 291, 25));
        Estado = new QLabel(page_3);
        Estado->setObjectName(QStringLiteral("Estado"));
        Estado->setGeometry(QRect(86, 520, 151, 20));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        label_4 = new QLabel(page_4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 10, 81, 17));
        pushButton_7 = new QPushButton(page_4);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(100, 10, 81, 71));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/Imagenes/agregarFamilia.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_7->setIcon(icon4);
        pushButton_7->setIconSize(QSize(75, 60));
        pushButton_8 = new QPushButton(page_4);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(300, 10, 81, 71));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/Imagenes/modificar.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_8->setIcon(icon5);
        pushButton_8->setIconSize(QSize(75, 70));
        pushButton_9 = new QPushButton(page_4);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(400, 10, 81, 71));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/Imagenes/eliminar.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_9->setIcon(icon6);
        pushButton_9->setIconSize(QSize(75, 75));
        dock_albergue = new QStackedWidget(page_4);
        dock_albergue->setObjectName(QStringLiteral("dock_albergue"));
        dock_albergue->setGeometry(QRect(10, 90, 561, 461));
        dock_albergue->setFrameShape(QFrame::Box);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        label_6 = new QLabel(page_7);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 10, 111, 17));
        label_14 = new QLabel(page_7);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 50, 171, 17));
        familia_albergue = new QLineEdit(page_7);
        familia_albergue->setObjectName(QStringLiteral("familia_albergue"));
        familia_albergue->setGeometry(QRect(180, 50, 221, 25));
        stackedWidget_2 = new QStackedWidget(page_7);
        stackedWidget_2->setObjectName(QStringLiteral("stackedWidget_2"));
        stackedWidget_2->setGeometry(QRect(10, 90, 531, 181));
        page_11 = new QWidget();
        page_11->setObjectName(QStringLiteral("page_11"));
        label_15 = new QLabel(page_11);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 10, 67, 17));
        nombre_familia = new QLineEdit(page_11);
        nombre_familia->setObjectName(QStringLiteral("nombre_familia"));
        nombre_familia->setGeometry(QRect(100, 10, 241, 25));
        label_16 = new QLabel(page_11);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 60, 67, 17));
        apellidos_familia = new QLineEdit(page_11);
        apellidos_familia->setObjectName(QStringLiteral("apellidos_familia"));
        apellidos_familia->setGeometry(QRect(100, 50, 241, 25));
        label_17 = new QLabel(page_11);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 100, 67, 17));
        edad_familia = new QLineEdit(page_11);
        edad_familia->setObjectName(QStringLiteral("edad_familia"));
        edad_familia->setGeometry(QRect(100, 90, 91, 25));
        label_18 = new QLabel(page_11);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(210, 90, 67, 17));
        btn_agregarFamilia = new QPushButton(page_11);
        btn_agregarFamilia->setObjectName(QStringLiteral("btn_agregarFamilia"));
        btn_agregarFamilia->setGeometry(QRect(370, 10, 121, 101));
        genero_familia = new QLineEdit(page_11);
        genero_familia->setObjectName(QStringLiteral("genero_familia"));
        genero_familia->setGeometry(QRect(260, 90, 81, 25));
        stackedWidget_2->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName(QStringLiteral("page_12"));
        stackedWidget_2->addWidget(page_12);
        dock_albergue->addWidget(page_7);
        page_10 = new QWidget();
        page_10->setObjectName(QStringLiteral("page_10"));
        label_9 = new QLabel(page_10);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 10, 67, 17));
        nombre_individuo = new QLineEdit(page_10);
        nombre_individuo->setObjectName(QStringLiteral("nombre_individuo"));
        nombre_individuo->setGeometry(QRect(110, 120, 241, 25));
        apellidos_individuo = new QLineEdit(page_10);
        apellidos_individuo->setObjectName(QStringLiteral("apellidos_individuo"));
        apellidos_individuo->setGeometry(QRect(110, 160, 241, 25));
        label_24 = new QLabel(page_10);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(30, 210, 67, 17));
        edad_individuo = new QLineEdit(page_10);
        edad_individuo->setObjectName(QStringLiteral("edad_individuo"));
        edad_individuo->setGeometry(QRect(110, 200, 91, 25));
        label_25 = new QLabel(page_10);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(20, 170, 67, 17));
        label_26 = new QLabel(page_10);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(220, 200, 67, 17));
        btn_agregarPersona = new QPushButton(page_10);
        btn_agregarPersona->setObjectName(QStringLiteral("btn_agregarPersona"));
        btn_agregarPersona->setGeometry(QRect(380, 120, 121, 101));
        label_27 = new QLabel(page_10);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 120, 67, 17));
        label_28 = new QLabel(page_10);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 90, 201, 17));
        dpi_individuo = new QLineEdit(page_10);
        dpi_individuo->setObjectName(QStringLiteral("dpi_individuo"));
        dpi_individuo->setGeometry(QRect(240, 80, 261, 25));
        label_37 = new QLabel(page_10);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 50, 67, 17));
        dpi_familia = new QLineEdit(page_10);
        dpi_familia->setObjectName(QStringLiteral("dpi_familia"));
        dpi_familia->setGeometry(QRect(100, 50, 401, 25));
        genero_individuo = new QLineEdit(page_10);
        genero_individuo->setObjectName(QStringLiteral("genero_individuo"));
        genero_individuo->setGeometry(QRect(280, 200, 71, 25));
        dock_albergue->addWidget(page_10);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        label_7 = new QLabel(page_8);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 10, 67, 17));
        dock_familia = new QStackedWidget(page_8);
        dock_familia->setObjectName(QStringLiteral("dock_familia"));
        dock_familia->setGeometry(QRect(10, 40, 541, 401));
        page_13 = new QWidget();
        page_13->setObjectName(QStringLiteral("page_13"));
        dock_familia->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName(QStringLiteral("page_14"));
        Cfamilia_modificar = new QComboBox(page_14);
        Cfamilia_modificar->setObjectName(QStringLiteral("Cfamilia_modificar"));
        Cfamilia_modificar->setGeometry(QRect(110, 20, 121, 25));
        label_29 = new QLabel(page_14);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 30, 67, 17));
        label_30 = new QLabel(page_14);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 70, 81, 17));
        cIndividuo_modificar = new QComboBox(page_14);
        cIndividuo_modificar->setObjectName(QStringLiteral("cIndividuo_modificar"));
        cIndividuo_modificar->setGeometry(QRect(110, 70, 121, 25));
        label_31 = new QLabel(page_14);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 140, 67, 17));
        label_32 = new QLabel(page_14);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 180, 67, 17));
        label_33 = new QLabel(page_14);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 220, 67, 17));
        label_34 = new QLabel(page_14);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(190, 210, 67, 17));
        nombre_modificar = new QLineEdit(page_14);
        nombre_modificar->setObjectName(QStringLiteral("nombre_modificar"));
        nombre_modificar->setGeometry(QRect(110, 130, 271, 25));
        apellidos_modificar = new QLineEdit(page_14);
        apellidos_modificar->setObjectName(QStringLiteral("apellidos_modificar"));
        apellidos_modificar->setGeometry(QRect(110, 170, 271, 25));
        edad_modificar = new QLineEdit(page_14);
        edad_modificar->setObjectName(QStringLiteral("edad_modificar"));
        edad_modificar->setGeometry(QRect(70, 210, 81, 25));
        genero_modificar = new QLineEdit(page_14);
        genero_modificar->setObjectName(QStringLiteral("genero_modificar"));
        genero_modificar->setGeometry(QRect(270, 210, 113, 25));
        pushButton_17 = new QPushButton(page_14);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(20, 280, 141, 25));
        pushButton_18 = new QPushButton(page_14);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(380, 0, 89, 25));
        pushButton_19 = new QPushButton(page_14);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(358, 60, 111, 25));
        pushButton_20 = new QPushButton(page_14);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(400, 110, 89, 81));
        dock_familia->addWidget(page_14);
        dock_albergue->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName(QStringLiteral("page_9"));
        label_8 = new QLabel(page_9);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 10, 67, 17));
        label_35 = new QLabel(page_9);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 60, 67, 17));
        cFamilia_eliminar = new QComboBox(page_9);
        cFamilia_eliminar->setObjectName(QStringLiteral("cFamilia_eliminar"));
        cFamilia_eliminar->setGeometry(QRect(150, 50, 161, 25));
        Cindividuo_eliminar = new QComboBox(page_9);
        Cindividuo_eliminar->setObjectName(QStringLiteral("Cindividuo_eliminar"));
        Cindividuo_eliminar->setGeometry(QRect(150, 90, 161, 25));
        label_36 = new QLabel(page_9);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 100, 67, 17));
        eliminar_familia = new QPushButton(page_9);
        eliminar_familia->setObjectName(QStringLiteral("eliminar_familia"));
        eliminar_familia->setGeometry(QRect(30, 140, 461, 71));
        eliminar_familia_2 = new QPushButton(page_9);
        eliminar_familia_2->setObjectName(QStringLiteral("eliminar_familia_2"));
        eliminar_familia_2->setGeometry(QRect(30, 220, 461, 71));
        pushButton_21 = new QPushButton(page_9);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(350, 50, 131, 25));
        pushButton_22 = new QPushButton(page_9);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(350, 90, 131, 25));
        dock_albergue->addWidget(page_9);
        pushButton_10 = new QPushButton(page_4);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(200, 10, 81, 71));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/Imagenes/agregarPersona.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_10->setIcon(icon7);
        pushButton_10->setIconSize(QSize(60, 75));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        label_5 = new QLabel(page_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 10, 131, 17));
        label_20 = new QLabel(page_5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 60, 71, 17));
        acopio_categoria = new QLineEdit(page_5);
        acopio_categoria->setObjectName(QStringLiteral("acopio_categoria"));
        acopio_categoria->setGeometry(QRect(120, 50, 201, 25));
        label_21 = new QLabel(page_5);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 110, 67, 17));
        acopio_nombre = new QLineEdit(page_5);
        acopio_nombre->setObjectName(QStringLiteral("acopio_nombre"));
        acopio_nombre->setGeometry(QRect(120, 100, 201, 25));
        label_22 = new QLabel(page_5);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(20, 150, 67, 17));
        spinBox = new QSpinBox(page_5);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(120, 140, 81, 26));
        pushButton_26 = new QPushButton(page_5);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(80, 200, 211, 25));
        pushButton_27 = new QPushButton(page_5);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(370, 50, 151, 131));
        textEdit_2 = new QTextEdit(page_5);
        textEdit_2->setObjectName(QStringLiteral("textEdit_2"));
        textEdit_2->setGeometry(QRect(20, 240, 531, 371));
        pushButton_37 = new QPushButton(page_5);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(400, 200, 89, 25));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        label_19 = new QLabel(page_6);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 10, 67, 17));
        pushButton_23 = new QPushButton(page_6);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(10, 40, 171, 25));
        gridLayoutWidget = new QWidget(page_6);
        gridLayoutWidget->setObjectName(QStringLiteral("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(10, 80, 551, 491));
        gridLayout = new QGridLayout(gridLayoutWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        gridLayout->setContentsMargins(0, 0, 0, 0);
        pushButton_32 = new QPushButton(page_6);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(250, 40, 281, 25));
        line_6 = new QFrame(page_6);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(200, 10, 3, 61));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        puntoa = new QComboBox(page_6);
        puntoa->setObjectName(QStringLiteral("puntoa"));
        puntoa->setGeometry(QRect(280, 10, 86, 25));
        puntob = new QComboBox(page_6);
        puntob->setObjectName(QStringLiteral("puntob"));
        puntob->setGeometry(QRect(460, 10, 86, 25));
        label_48 = new QLabel(page_6);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(210, 20, 67, 17));
        label_49 = new QLabel(page_6);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(380, 20, 67, 17));
        stackedWidget->addWidget(page_6);
        page_15 = new QWidget();
        page_15->setObjectName(QStringLiteral("page_15"));
        label_50 = new QLabel(page_15);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(20, 10, 67, 17));
        label_57 = new QLabel(page_15);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(10, 40, 81, 17));
        label_58 = new QLabel(page_15);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(10, 70, 67, 17));
        label_59 = new QLabel(page_15);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 100, 67, 17));
        categoria_entrega = new QLineEdit(page_15);
        categoria_entrega->setObjectName(QStringLiteral("categoria_entrega"));
        categoria_entrega->setGeometry(QRect(100, 40, 151, 25));
        nombre_entrega = new QLineEdit(page_15);
        nombre_entrega->setObjectName(QStringLiteral("nombre_entrega"));
        nombre_entrega->setGeometry(QRect(100, 70, 151, 25));
        unidades_entrega = new QLineEdit(page_15);
        unidades_entrega->setObjectName(QStringLiteral("unidades_entrega"));
        unidades_entrega->setGeometry(QRect(100, 100, 151, 25));
        lst_entrega = new QTextEdit(page_15);
        lst_entrega->setObjectName(QStringLiteral("lst_entrega"));
        lst_entrega->setGeometry(QRect(320, 70, 231, 441));
        line_9 = new QFrame(page_15);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(283, 30, 20, 531));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        label_60 = new QLabel(page_15);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(320, 30, 67, 17));
        pushButton_35 = new QPushButton(page_15);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(30, 150, 221, 25));
        pushButton_36 = new QPushButton(page_15);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(30, 250, 241, 271));
        stackedWidget->addWidget(page_15);
        pushButton_5 = new QPushButton(centralWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(20, 380, 89, 71));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/Imagenes/medicina.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_5->setIcon(icon8);
        pushButton_5->setIconSize(QSize(75, 60));
        pushButton_6 = new QPushButton(centralWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(20, 470, 89, 71));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/Imagenes/localizacion-tienda-ropa.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_6->setIcon(icon9);
        pushButton_6->setIconSize(QSize(80, 100));
        pushButton_33 = new QPushButton(centralWidget);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(20, 560, 89, 61));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/Imagenes/entrega.png"), QSize(), QIcon::Normal, QIcon::On);
        pushButton_33->setIcon(icon10);
        pushButton_33->setIconSize(QSize(50, 65));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 752, 22));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);
        dock_albergue->setCurrentIndex(3);
        stackedWidget_2->setCurrentIndex(0);
        dock_familia->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        pushButton->setText(QString());
        pushButton_2->setText(QString());
        pushButton_3->setText(QString());
        pushButton_4->setText(QString());
        label->setText(QApplication::translate("MainWindow", "Locacion", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "Nombre", Q_NULLPTR));
        label_38->setText(QApplication::translate("MainWindow", "Codigo", Q_NULLPTR));
        label_39->setText(QApplication::translate("MainWindow", "Latitud", Q_NULLPTR));
        label_40->setText(QApplication::translate("MainWindow", "Longitud", Q_NULLPTR));
        label_41->setText(QApplication::translate("MainWindow", "Password", Q_NULLPTR));
        label_42->setText(QApplication::translate("MainWindow", "Nombre Archivo", Q_NULLPTR));
        label_43->setText(QApplication::translate("MainWindow", "Arista", Q_NULLPTR));
        label_44->setText(QApplication::translate("MainWindow", "Destino", Q_NULLPTR));
        label_45->setText(QApplication::translate("MainWindow", "Multiplicador", Q_NULLPTR));
        label_46->setText(QApplication::translate("MainWindow", "Inicio", Q_NULLPTR));
        pushButton_28->setText(QApplication::translate("MainWindow", "Enviar Locacion", Q_NULLPTR));
        pushButton_29->setText(QApplication::translate("MainWindow", "Enviar Arista", Q_NULLPTR));
        pushButton_30->setText(QApplication::translate("MainWindow", "Modificar", Q_NULLPTR));
        label_47->setText(QApplication::translate("MainWindow", "Codigo a Eliminar", Q_NULLPTR));
        pushButton_31->setText(QApplication::translate("MainWindow", "Eliminar", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "Donacion", Q_NULLPTR));
        label_52->setText(QApplication::translate("MainWindow", "Documento de Identificacion ", Q_NULLPTR));
        label_53->setText(QApplication::translate("MainWindow", "Nombres", Q_NULLPTR));
        label_54->setText(QApplication::translate("MainWindow", "Apellidos", Q_NULLPTR));
        label_55->setText(QApplication::translate("MainWindow", "Fecha", Q_NULLPTR));
        label_56->setText(QApplication::translate("MainWindow", "Monto", Q_NULLPTR));
        pushButton_34->setText(QApplication::translate("MainWindow", "Agregar", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "Informacion", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Ruta:", Q_NULLPTR));
        lineEdit->setText(QApplication::translate("MainWindow", "Seleccione Archivo....", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "Cargar Archivo", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "Mandar Archivo", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "Traer Localidades", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("MainWindow", "Mandar Archivo", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "Traer Donaciones", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Ruta:", Q_NULLPTR));
        lineEdit_2->setText(QApplication::translate("MainWindow", "Seleccione Archivo....", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("MainWindow", "Cargar Archivo", Q_NULLPTR));
        label_12->setText(QString());
        label_13->setText(QString());
        pushButton_24->setText(QApplication::translate("MainWindow", "Cifrar", Q_NULLPTR));
        pushButton_25->setText(QApplication::translate("MainWindow", "Decifrar", Q_NULLPTR));
        Carchivo_informacion->setText(QApplication::translate("MainWindow", "Cargar Archivo", Q_NULLPTR));
        label_51->setText(QApplication::translate("MainWindow", "Ruta", Q_NULLPTR));
        MArchivo_informacion->setText(QApplication::translate("MainWindow", "Mandar Archivo", Q_NULLPTR));
        archivo_informacion->setText(QApplication::translate("MainWindow", "Seleccione Archivo....", Q_NULLPTR));
        Estado->setText(QApplication::translate("MainWindow", "ESTADO", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "Albergues", Q_NULLPTR));
        pushButton_7->setText(QString());
        pushButton_8->setText(QString());
        pushButton_9->setText(QString());
        label_6->setText(QApplication::translate("MainWindow", "Agregar Familia", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Encargado de Familia", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "Nombre:", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "Apellidos:", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "Edad", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "Genero", Q_NULLPTR));
        btn_agregarFamilia->setText(QApplication::translate("MainWindow", "Agregar", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Agregar ", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "Edad", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "Apellidos:", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "Genero", Q_NULLPTR));
        btn_agregarPersona->setText(QApplication::translate("MainWindow", "Agregar", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "Nombre:", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "Documento de Ifentificacion ", Q_NULLPTR));
        label_37->setText(QApplication::translate("MainWindow", "Familia", Q_NULLPTR));
        genero_individuo->setText(QString());
        label_7->setText(QApplication::translate("MainWindow", "Modificar", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "Familia", Q_NULLPTR));
        label_30->setText(QApplication::translate("MainWindow", "Individuos", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "Nombre", Q_NULLPTR));
        label_32->setText(QApplication::translate("MainWindow", "Apellidos", Q_NULLPTR));
        label_33->setText(QApplication::translate("MainWindow", "Edad", Q_NULLPTR));
        label_34->setText(QApplication::translate("MainWindow", "Genero", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("MainWindow", "Modificar", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("MainWindow", "getFamilias", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("MainWindow", "getIndividuos", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("MainWindow", "Graficar", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Eliminar", Q_NULLPTR));
        label_35->setText(QApplication::translate("MainWindow", "Familia", Q_NULLPTR));
        label_36->setText(QApplication::translate("MainWindow", "Individuo", Q_NULLPTR));
        eliminar_familia->setText(QApplication::translate("MainWindow", "Eliminar Familia ", Q_NULLPTR));
        eliminar_familia_2->setText(QApplication::translate("MainWindow", "Eliminar Individuo", Q_NULLPTR));
        pushButton_21->setText(QApplication::translate("MainWindow", "get Familia", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("MainWindow", "get individuo", Q_NULLPTR));
        pushButton_10->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "Centros de Acopio", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "Categoria:", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "Nombre:", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "Cantidad:", Q_NULLPTR));
        pushButton_26->setText(QApplication::translate("MainWindow", "Efectuar Donacion", Q_NULLPTR));
        pushButton_27->setText(QApplication::translate("MainWindow", "Imprimir", Q_NULLPTR));
        pushButton_37->setText(QApplication::translate("MainWindow", "Actualizar", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "Mapas ", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("MainWindow", "Traer Localidades", Q_NULLPTR));
        pushButton_32->setText(QApplication::translate("MainWindow", "Trazar camino", Q_NULLPTR));
        label_48->setText(QApplication::translate("MainWindow", "Punto A", Q_NULLPTR));
        label_49->setText(QApplication::translate("MainWindow", "Punto B", Q_NULLPTR));
        label_50->setText(QApplication::translate("MainWindow", "Entrega", Q_NULLPTR));
        label_57->setText(QApplication::translate("MainWindow", "Categoria", Q_NULLPTR));
        label_58->setText(QApplication::translate("MainWindow", "Nombre", Q_NULLPTR));
        label_59->setText(QApplication::translate("MainWindow", "Unidades", Q_NULLPTR));
        label_60->setText(QApplication::translate("MainWindow", "Listas", Q_NULLPTR));
        pushButton_35->setText(QApplication::translate("MainWindow", "Agregar", Q_NULLPTR));
        pushButton_36->setText(QApplication::translate("MainWindow", "ENVIAR", Q_NULLPTR));
        pushButton_5->setText(QString());
        pushButton_6->setText(QString());
        pushButton_33->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
